---
title: "Lab 2: Regression to Study the Spread of Covid-19"
author: 'w203: Statistics for Data Science'
date: "10/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Your introduction should present a research question and explain the concept that you're attempting to measure and how it will be operationalized. This section should pave the way for the body of the report, preparing the reader to understand why the models are constructed the way that they are. It is not enough to simply say "We are looking for policies that help against COVID."  Your introduction must do work for you, focusing the reader on a specific measurement goal, making them care about it, and propelling the narrative forward. This is also good time to put your work into context, discuss cross-cutting issues, and assess the overall appropriateness of the data.
```

## 2. Model Building

### EDA

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# You will next build a set of models to investigate your research question, documenting your decisions. Here are some things to keep in mind during your model building process:
# 
# 1. *What do you want to measure*? Make sure you identify one key variable (possibly more in rare cases) that will allow you to derive conclusions relevant to your research question, and include this variables in all model specifications.
# 2. Is your modeling goal one of description or explanation? 
# 3. What [covariates](https://en.wikipedia.org/wiki/Dependent_and_independent_variables#Statistics_synonyms) help you achieve your modeling goals? What covariates are problematic, either due to *collinearity*, or because they will absorb some of a causal effect you want to measure?
# 4. What *transformations*, if any, should you apply to each variable? These transformations might reveal linearities in the data, make your results relevant, or help you meet model assumptions.
# 5. Are your choices supported by exploratory data analysis (*EDA*)? You will likely start with some general EDA to *detect anomalies* (missing values, top-coded variables, etc.). From then on, your EDA should be interspersed with your model building. Use visual tools to *guide* your decisions. You can also leverage statistical *tests* to help assess whether variables, or groups of variables, are improving model fit.
# 
# At the same time, it is important to remember that you are not trying to create one perfect model. You will create several specifications, giving the reader a sense of how robust (or sensitive) your results are to modeling choices, and to show that you're not just cherry-picking the specification that leads to the largest effects.
# 
# At a minimum, you should include the following three specifications:
# 
# 1. **Limited Model**: A model that includes *only the key variable* you want to measure and nothing (or almost nothing) else. This variables might be transformed, as determined by your EDA, but the model should include the absolute minimum number of covariates (perhaps one, or at most two-three, covariates if they are so crucial that it would be unreasonable to omit them). 
# 1. **Model Two**: A model that includes *key explanatory variables and covariates that you believe advance your modeling* goals without introducing too much multicollinearity or causing other issues. This model should strike a balance between accuracy and parsimony and reflect your best understanding of the relationships among key variables.
# 1. **Model Three**: A model that includes the *previous covariates, and many other covariates*, erring on the side of inclusion. A key purpose of this model is to evaluate how parameters of interest change (if at all) when additional, potentially colinear variables are included in the model specification.
# 
# Although the models have different emphases, each one must still be a reasonable choice given your modeling goals.  The idea is to choose models that encircle the space of reasonable modeling choices, and to give an overall understanding of how these choices impact results.
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
## Load packages 
library(dplyr)
library(magrittr)
library(lubridate)
library(ggplot2)
library(openxlsx)
library(lmtest)
library(sandwich)
library(stargazer)

## Import datasets
mobility <- read.csv('../data/raw/2020_US_Region_Mobility_Report.csv',
                     stringsAsFactors = F)
stateInfo <- read.xlsx('../data/raw/COVID-19 US state policy database 3_17_2021.xlsx',
                      sheet = 1, detectDates = T) %>%
   ## Filter out the filler rows
  filter(!(STATE %in% c('State', 'category', 'type', 'unit'))) 

## Subset mobility data down to only state rows and convert the date to a date
stateLevel <- mobility %>% filter(sub_region_1 != '', 
                                  sub_region_2 == '') %>%
                           mutate(Date = ymd(date))

rm(mobility)

```

### Model  1
```{r}
modDat <- stateLevel %>% 
  filter(Date >= '2020-04-01',
         Date <= '2020-08-01') %>%
  group_by(sub_region_1) %>%
  summarise(y_var = mean(retail_and_recreation_percent_change_from_baseline)) %>%
  left_join(stateInfo, by = c('sub_region_1' = 'STATE')) %>%
  mutate(stay = case_when(STAYHOME > 0 ~ '1',
                          STAYHOMENOGP > 0 ~ '0.5', 
                          TRUE ~ '0'),
         length = case_when(STAYHOME > 0 ~ ymd(END_STHM) - ymd(STAYHOME),
                            STAYHOMENOGP > 0 ~ ymd(END_STHM) - ymd(STAYHOMENOGP),
                            TRUE ~ 0))

mod1 <- lm(y_var ~ stay:length
          , data = modDat)
coeftest(mod1, vcov = vcovHC(mod1))
```


### Model 2

### Model 3

### Regression Table and Interpretation
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# 
# You should display all of your model specifications in a regression table, using a package like [`stargazer`](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf) to format your output. It should be easy for the reader to find the coefficients that represent key effects at the top of the regression table, and scan horizontally to see how they change from specification to specification. Make sure that you display the most appropriate standard errors in your table, along with significance stars.
# 
# In your text, comment on both *statistical significance and practical significance*. You may want to include statistical tests besides the standard t-tests for regression coefficients.
```

## 4. Limitations

````{r, echo=FALSE, warning=FALSE, message=FALSE}
# As a team, evaluate all of the CLM assumptions that must hold for your model. However, do not report an exhaustive examination all 5 CLM assumption. Instead, bring forward only those assumptions that you think pose significant problems for your analysis. For each problem that you identify, describe the statistical consequences. If you are able to identify any strategies to mitigate the consequences, explain these strategies. 
# 
# Note that you may need to change your model specifications in response to violations of the CLM. 
```

## 5. Discussion of Omitted Variables

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# If the team has taken up an explanatory (i.e. causal) question to evaluate, then identify what you think are the 5 most important *omitted variables* that bias results you care about. For each variable, you should *reason about the direction of bias* caused by omitting this variable. If you can argue whether the bias is large or small, that is even better. State whether you have any variables available that may proxy (even imperfectly) for the omitted variable. Pay particular attention to whether each omitted variable bias is *towards zero or away from zero*. You will use this information to judge whether the effects you find are likely to be real, or whether they might be entirely an artifact of omitted variable bias.
```

## 6. Conclusion

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Make sure that you end your report with a discussion that distills key insights from your estimates and addresses your research question.
```